#!/usr/bin/env node
/**
 * write-session — Stop hook. Maintains a BOUNDED SESSION.md at zero model tokens.
 *
 * The checkpoint is split in half and the halves have different owners:
 *   - the MECHANICAL half (git state + a truncated tail of recent turns) is free and
 *     regenerated by this hook on every turn end;
 *   - the NARRATIVE half (decisions, dead ends, next steps) needs the model and is
 *     written once by the /write-session command. This hook never touches it.
 *
 * Why bounded and not append-only: SESSION.md is read into a fresh session's PREFIX
 * and re-read on every subsequent request there. An append-only log makes the save
 * free but the restore expensive — a cost inversion. Everything here is capped.
 *
 * Input (stdin JSON, verified against claude.exe 2.1.224):
 *   session_id, transcript_path, cwd, hook_event_name:"Stop", stop_hook_active,
 *   last_assistant_message  ("Text content of the last assistant message before
 *   stopping. Avoids the need to read and parse the transcript file.")
 * Older builds may omit last_assistant_message; we fall back to a bounded tail read
 * of transcript_path.
 *
 * Writes nothing to stdout, so it never injects tokens into the conversation.
 * Never blocks: all failures are swallowed and the process always exits 0.
 *
 * Configuration — environment variables only. No config file, no prompts.
 *   WRITE_SESSION=0                  disable entirely (CLAUDE_SESSION_MD=0 also honored)
 *   WRITE_SESSION_LOCATION=home      never write inside the repo; keep SESSION.md under
 *                                    the state dir instead (default: repo)
 *   WRITE_SESSION_GIT_EXCLUDE=0      do not touch .git/info/exclude
 *   WRITE_SESSION_MAX_TURNS=6        ring buffer depth        (1-50)
 *   WRITE_SESSION_MAX_TURN_CHARS=400 per-turn truncation      (80-4000)
 *   WRITE_SESSION_MAX_DIRTY=15       dirty files listed       (1-200)
 *   WRITE_SESSION_STATE_DIR=<path>   override ~/.claude/write-session
 */

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const ENV = process.env;

/** Numeric env override. `|| ''` not `?? ''`: a blank-but-present var must fall back. */
function num(name, dflt, min, max) {
  const v = parseInt(ENV[name] || '', 10);
  return Number.isFinite(v) && v >= min && v <= max ? v : dflt;
}
const isOff = (name) => (ENV[name] || '').toLowerCase() === '0' || (ENV[name] || '').toLowerCase() === 'false';

const MAX_TURNS = num('WRITE_SESSION_MAX_TURNS', 6, 1, 50);
const MAX_TURN_CHARS = num('WRITE_SESSION_MAX_TURN_CHARS', 400, 80, 4000);
const MAX_DIRTY = num('WRITE_SESSION_MAX_DIRTY', 15, 1, 200);
const MIN_TURN_CHARS = 15; // skip "Done." and friends
const MAX_SUBJECT = 72;
const GIT_TIMEOUT = 4000;
const STATE_TTL_MS = 7 * 24 * 60 * 60 * 1000; // prune per-session turn files after a week
const LOCK_STALE_MS = 15000;
const LOCK_WAIT_MS = 3000;

const AUTO_START = '<!-- session-md:auto:start -->';
const AUTO_END = '<!-- session-md:auto:end -->';
const NARR_START = '<!-- session-md:narrative:start -->';
const NARR_END = '<!-- session-md:narrative:end -->';

const NARRATIVE_SEED = `## Where we are

_Not written yet — run \`/write-session\` before \`/clear\` to fill this in._

## Decisions made

## Dead ends (do not retry)

## Next steps

## Key files
`;

function git(cwd, args) {
  try {
    return execFileSync('git', ['-C', cwd, ...args], {
      encoding: 'utf8',
      timeout: GIT_TIMEOUT,
      stdio: ['ignore', 'pipe', 'ignore'],
      windowsHide: true,
    }).trim();
  } catch {
    return '';
  }
}

function stamp(d = new Date()) {
  const p = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`;
}

function slug(s) {
  return String(s).replace(/[^A-Za-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 120) || 'root';
}

function truncate(s, n) {
  return s.length <= n ? s : s.slice(0, n - 1).trimEnd() + '…';
}

/** Collapse an assistant message to a single dense line. */
function condense(msg) {
  return String(msg)
    .replace(/```[\s\S]*?```/g, '⟨code⟩') // fenced blocks carry little state
    .replace(/^\s*[-*]\s+/gm, '· ')
    .replace(/[#>|]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function sleepSync(ms) {
  try {
    Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
  } catch {
    /* SharedArrayBuffer unavailable — spin-free no-op, we just retry sooner */
  }
}

/**
 * Cross-process mutex via atomic mkdir. Two Claude Code sessions in one repo both
 * run this hook; without it they race on the read-splice-write of SESSION.md and one
 * can drop the other's narrative. Fails OPEN — a lock we cannot take is not a reason
 * to skip the checkpoint.
 */
function withLock(lockDir, fn) {
  const start = Date.now();
  for (;;) {
    try {
      fs.mkdirSync(lockDir);
      break;
    } catch (e) {
      if (e.code !== 'EEXIST') return fn();
      let age = Infinity;
      try {
        age = Date.now() - fs.statSync(lockDir).mtimeMs;
      } catch {
        /* vanished between EEXIST and stat — loop and retry the mkdir */
      }
      if (age > LOCK_STALE_MS) {
        try {
          fs.rmdirSync(lockDir);
        } catch {
          /* someone else broke it first */
        }
        continue;
      }
      if (Date.now() - start > LOCK_WAIT_MS) return fn();
      sleepSync(60);
    }
  }
  try {
    return fn();
  } finally {
    try {
      fs.rmdirSync(lockDir);
    } catch {
      /* already gone */
    }
  }
}

/** Same-volume rename is atomic: a concurrent reader never sees a torn file. */
function writeAtomic(target, content) {
  const tmp = `${target}.tmp-${process.pid}`;
  try {
    fs.writeFileSync(tmp, content);
    fs.renameSync(tmp, target);
  } catch {
    try {
      fs.writeFileSync(target, content);
    } catch {
      /* give up silently */
    }
    try {
      fs.unlinkSync(tmp);
    } catch {
      /* nothing to clean */
    }
  }
}

/**
 * Fallback when the harness does not supply last_assistant_message. Bounded tail read
 * of the transcript: last 512 KB, scanned backwards for the newest assistant message
 * carrying a text block. The first line of the window is usually truncated and simply
 * fails to parse, which is fine.
 */
function lastAssistantFromTranscript(transcriptPath) {
  if (!transcriptPath) return '';
  try {
    const st = fs.statSync(transcriptPath);
    const N = Math.min(st.size, 512 * 1024);
    if (!N) return '';
    const fd = fs.openSync(transcriptPath, 'r');
    const buf = Buffer.alloc(N);
    fs.readSync(fd, buf, 0, N, st.size - N);
    fs.closeSync(fd);
    const lines = buf.toString('utf8').split('\n');
    for (let i = lines.length - 1; i >= 0; i--) {
      const L = lines[i].trim();
      if (!L.startsWith('{')) continue;
      let o;
      try {
        o = JSON.parse(L);
      } catch {
        continue;
      }
      if (o.type !== 'assistant' || !o.message || !Array.isArray(o.message.content)) continue;
      const text = o.message.content
        .filter((b) => b && b.type === 'text' && b.text)
        .map((b) => b.text)
        .join('\n')
        .trim();
      if (text) return text;
    }
  } catch {
    /* unreadable transcript is not an error */
  }
  return '';
}

/**
 * Turn history is stored ONE FILE PER SESSION, then merged at read time. Sharing a
 * single ring buffer across concurrent sessions would make every write a
 * read-modify-write race; per-session files make each writer independent.
 */
function readTurns(stateDir) {
  let names = [];
  try {
    names = fs.readdirSync(stateDir).filter((n) => /^turns-.+\.json$/.test(n));
  } catch {
    return [];
  }
  const all = [];
  const now = Date.now();
  for (const n of names) {
    const f = path.join(stateDir, n);
    try {
      if (now - fs.statSync(f).mtimeMs > STATE_TTL_MS) {
        fs.unlinkSync(f);
        continue;
      }
      const parsed = JSON.parse(fs.readFileSync(f, 'utf8'));
      if (Array.isArray(parsed.turns)) all.push(...parsed.turns);
    } catch {
      /* skip unreadable/corrupt state file */
    }
  }
  return all
    .filter((t) => t && typeof t.m === 'string')
    .sort((a, b) => (a.ts || 0) - (b.ts || 0))
    .slice(-MAX_TURNS);
}

/**
 * Keep SESSION.md out of commits without touching a tracked .gitignore:
 * .git/info/exclude is local-only and never shows in a diff.
 * Opt out with WRITE_SESSION_GIT_EXCLUDE=0 if your team commits SESSION.md.
 */
function ensureExcluded(repoRoot) {
  const gitDir = git(repoRoot, ['rev-parse', '--absolute-git-dir']);
  if (!gitDir) return;
  const excludeFile = path.join(gitDir, 'info', 'exclude');
  try {
    const cur = fs.existsSync(excludeFile) ? fs.readFileSync(excludeFile, 'utf8') : '';
    if (/^\/?SESSION\.md\s*$/m.test(cur)) return;
    fs.mkdirSync(path.dirname(excludeFile), { recursive: true });
    fs.appendFileSync(
      excludeFile,
      (cur && !cur.endsWith('\n') ? '\n' : '') +
        '\n# write-session (local scratch checkpoint)\n/SESSION.md\n',
    );
  } catch {
    /* read-only .git, submodule, whatever — not fatal */
  }
}

function buildGitBlock(cwd, repoRoot) {
  if (!repoRoot) return `- Not a git repository (\`${cwd}\`).`;

  const statusRaw = git(repoRoot, ['status', '--porcelain=v1', '-b']);
  const lines = statusRaw ? statusRaw.split(/\r?\n/) : [];
  const branchLine = lines[0] && lines[0].startsWith('## ') ? lines[0].slice(3) : '(unknown)';
  const dirty = lines.slice(1).filter(Boolean);

  const head = git(repoRoot, ['log', '-1', '--format=%h%x09%s']);
  const [headSha, headSubj = ''] = head ? head.split('\t') : ['(no commits)'];
  const shortstat = git(repoRoot, ['diff', '--shortstat', 'HEAD']);
  const recent = git(repoRoot, ['log', '-5', '--format=%h%x09%s']);

  const out = [];
  out.push(`- **Branch** \`${branchLine}\``);
  out.push(`- **HEAD** \`${headSha}\` ${truncate(headSubj, MAX_SUBJECT)}`.trimEnd());
  out.push(`- **Root** \`${repoRoot}\``);

  if (dirty.length) {
    out.push(`- **Dirty** ${dirty.length} file(s)${shortstat ? ` — ${shortstat}` : ''}`);
    for (const d of dirty.slice(0, MAX_DIRTY)) out.push(`  - \`${d}\``);
    if (dirty.length > MAX_DIRTY) out.push(`  - _…and ${dirty.length - MAX_DIRTY} more_`);
  } else {
    out.push('- **Dirty** clean');
  }

  if (recent) {
    out.push('- **Recent commits**');
    for (const r of recent.split(/\r?\n/)) {
      const [sha, subj = ''] = r.split('\t');
      out.push(`  - \`${sha}\` ${truncate(subj, MAX_SUBJECT)}`.trimEnd());
    }
  }
  return out.join('\n');
}

function buildAutoBlock({ cwd, repoRoot, sessionId, turns }) {
  const multi = new Set(turns.map((t) => t.s)).size > 1;
  const turnLines = turns.length
    ? turns.map((t) => `- **${t.t}**${multi ? ` \`${t.s}\`` : ''} ${t.m}`).join('\n')
    : '- _no turns recorded yet_';

  return [
    AUTO_START,
    '',
    '_Auto-maintained by the `write-session` Stop hook — regenerated every turn._',
    '_Do not hand-edit inside this block; everything below the end marker survives._',
    '',
    `**Updated** ${stamp()} · **cwd** \`${cwd}\` · **session** \`${String(sessionId).slice(0, 8)}\``,
    '',
    '## Git',
    '',
    buildGitBlock(cwd, repoRoot),
    '',
    `## Recent turns (last ${MAX_TURNS}, oldest first, truncated)`,
    '',
    turnLines,
    '',
    AUTO_END,
  ].join('\n');
}

function frame(title, autoBlock, narrative) {
  return [
    `# SESSION — ${title}`,
    '',
    '_Scratch state for resuming after `/clear`. Durable follow-ups belong in `TODOS.md`._',
    '',
    autoBlock,
    '',
    NARR_START,
    '',
    narrative,
    '',
    NARR_END,
    '',
  ].join('\n');
}

/** Replace only the auto region; preserve everything else byte-for-byte. */
function spliceAuto(existing, autoBlock, title) {
  if (existing) {
    const s = existing.indexOf(AUTO_START);
    const e = existing.indexOf(AUTO_END);
    if (s !== -1 && e !== -1 && e > s) {
      return existing.slice(0, s) + autoBlock + existing.slice(e + AUTO_END.length);
    }
    // File exists but has no markers (predates the hook, or something overwrote it
    // wholesale). Adopt it: keep the body verbatim as the narrative, drop its H1.
    const body = existing.replace(/^#\s+.*(\r?\n)+/, '').trim();
    return frame(title, autoBlock, body || NARRATIVE_SEED.trim());
  }
  return frame(title, autoBlock, NARRATIVE_SEED.trim());
}

function main() {
  if (isOff('WRITE_SESSION') || isOff('CLAUDE_SESSION_MD')) return;

  let input = {};
  try {
    input = JSON.parse(fs.readFileSync(0, 'utf8') || '{}');
  } catch {
    return;
  }
  if (input.hook_event_name && input.hook_event_name !== 'Stop') return;

  const cwd = input.cwd || process.cwd();
  const sessionId = String(input.session_id || 'unknown');
  const sid = slug(sessionId).slice(0, 8) || 'unknown';
  const repoRoot = git(cwd, ['rev-parse', '--show-toplevel']);

  // Location rule (mirrored in commands/write-session.md): repo root when inside a
  // repo, else a per-cwd dir under the state root. WRITE_SESSION_LOCATION=home keeps
  // it out of the repo entirely.
  // NB: the state root is NOT ~/.claude/sessions — Claude Code owns that directory
  // for its live session registry (pid/sessionId/status JSON) and writing there
  // would collide with it.
  const stateRoot = ENV.WRITE_SESSION_STATE_DIR || path.join(os.homedir(), '.claude', 'write-session');
  const anchor = repoRoot || cwd;
  const stateDir = path.join(stateRoot, slug(anchor));
  const inRepo = !!repoRoot && (ENV.WRITE_SESSION_LOCATION || 'repo').toLowerCase() !== 'home';
  const target = inRepo ? path.join(repoRoot, 'SESSION.md') : path.join(stateDir, 'SESSION.md');

  fs.mkdirSync(stateDir, { recursive: true });

  // Append this turn to THIS session's own ring buffer — no cross-session contention.
  const raw = input.last_assistant_message || lastAssistantFromTranscript(input.transcript_path);
  const msg = condense(raw);
  if (msg.length >= MIN_TURN_CHARS) {
    const line = truncate(msg, MAX_TURN_CHARS);
    const own = path.join(stateDir, `turns-${sid}.json`);
    let mine = [];
    try {
      const parsed = JSON.parse(fs.readFileSync(own, 'utf8'));
      if (Array.isArray(parsed.turns)) mine = parsed.turns;
    } catch {
      /* first turn of this session */
    }
    const last = mine[mine.length - 1];
    if (!last || last.m !== line) {
      mine.push({ ts: Date.now(), t: stamp(), s: sid, m: line });
      mine = mine.slice(-MAX_TURNS);
      writeAtomic(own, JSON.stringify({ turns: mine }));
    }
  }

  const title = repoRoot ? path.basename(repoRoot) : path.basename(cwd) || cwd;

  withLock(path.join(stateDir, '.lock'), () => {
    if (inRepo && !isOff('WRITE_SESSION_GIT_EXCLUDE')) ensureExcluded(repoRoot);
    const turns = readTurns(stateDir);
    const autoBlock = buildAutoBlock({ cwd, repoRoot, sessionId, turns });
    const existing = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
    writeAtomic(target, spliceAuto(existing, autoBlock, title));
  });
}

try {
  main();
} catch {
  /* never block the turn */
}
process.exit(0);
